version: '2'

services:
  sql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: analytics
    ports:
      - "3306:3306"
    networks:
      - appnetwork

networks:
   appnetwork:
      driver: bridge